### PR TITLE
add snappy to darkn.bio

### PR DESCRIPTION
**Pull request by NotDarkn**
self-explanatory really

### CODE REVIEW

**Comment by kxtzownsu** [comment]
@e9x this is so hot

**Comment by e9x** [comment]
I will look at this soon

**Comment by e9x** [comment]
thanks

**Comment by clm1919** [comment]
Not sure what the protocol is - but I wanted to publicly thank you making for "chrome100".  Feel free to delete this and just know that you are appreciated :-)

**Comment by e9x** [comment]
appreciate the support ♥️

**Comment by e9x** [comment]
@clm1919 thanks, I appreciate the support ♥️

**Comment by clm1919** [comment]
♥️

**Pull request merged**
